image: node:latest

stages:
  - build
  - deploy

variables:
  BUCKET_NAME: torin.design

cache:
  paths:
    - node_modules/

buildGatsby:
  stage: build
  script:
    - yarn install # install dependencies
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
    - public
  only:
    - master

deploys3:
  image: "python:3.6.6"  # We use python because there is a well-working AWS Sdk
  stage: deploy
  dependencies:
    - buildGatsby
  before_script:
    - pip install awscli # Install the SDK
  script:
    - aws s3 cp public s3://${BUCKET_NAME} --recursive
  environment:
    name: 's3-deploy'
    url: http://${BUCKET_NAME}.s3-website-ap-southeast-2.amazonaws.com/ # This is the url of the bucket we saved before
